// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Project1.Model;
//
//    var registered = Registered.FromJson(jsonString);

namespace Project1.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Registered
    {
        [JsonProperty("semester")]
        public string Semester { get; set; }

        [JsonProperty("year")]
        public string Year { get; set; }

        [JsonProperty("subjectName")]
        public string SubjectName { get; set; }

        [JsonProperty("subjectID")]
        public string SubjectId { get; set; }

        [JsonProperty("grade")]
        public string Grade { get; set; }
    }

    public partial class Registered
    {
        public static List<Registered> FromJson(string json) => JsonConvert.DeserializeObject<List<Registered>>(json, Project1.Model.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<Registered> self) => JsonConvert.SerializeObject(self, Project1.Model.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
