// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Project2.Model;
//
//    var usersData = UsersData.FromJson(jsonString);

namespace Project2.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class UsersData
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("gender")]
        public string Gender { get; set; }

        [JsonProperty("phone")]
        public string Phone { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("password")]
        public string Password { get; set; }

        [JsonProperty("year")]
        public long Year { get; set; }

        [JsonProperty("department")]
        public string Department { get; set; }

        [JsonProperty("address")]
        public string Address { get; set; }
    }

    public partial class UsersData
    {
        public static List<UsersData> FromJson(string json) => JsonConvert.DeserializeObject<List<UsersData>>(json, Project2.Model.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this List<UsersData> self) => JsonConvert.SerializeObject(self, Project2.Model.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
